#!/bin/bash

intltool-extract --type=gettext/glade usr/share/osdenios/deniosmenu/applications.ui
intltool-extract --type=gettext/glade usr/share/osdenios/deniosmenu/main.ui
intltool-extract --type=gettext/glade usr/share/osdenios/deniosmenu/places.ui
intltool-extract --type=gettext/glade usr/share/osdenios/deniosmenu/preferences.ui
intltool-extract --type=gettext/glade usr/share/osdenios/deniosmenu/recent.ui
intltool-extract --type=gettext/glade usr/share/osdenios/deniosmenu/system.ui

xgettext --language=Python --keyword=_ --keyword=N_ --output=deniosmenu.pot usr/lib/osdenios/deniosMenu/*.py usr/lib/osdenios/deniosMenu/plugins/*.py usr/share/osdenios/deniosmenu/*.ui.h

rm -rf usr/share/osdenios/deniosmenu/*.ui.h
